######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 13 14:31:09 2007
######################################################################

TEMPLATE = lib
TARGET = ircclient
DESTDIR = bin
DEPENDPATH += . src
INCLUDEPATH += . src
QT += network
# Input
HEADERS += src/ircclient.h
SOURCES += src/ircclient.cpp
