######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 30 23:01:47 2008
######################################################################

TEMPLATE = app
# CONFIG += plugin
TARGET = mirc
DESTDIR = bin
DEPENDPATH += . includes src
INCLUDEPATH += . includes

# Input
HEADERS += includes/mirc.h includes/parser.h includes/script.h
SOURCES += src/mirc.cpp \
 src/parser.cpp \
 src/script.cpp \
 src/main.cpp
