######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 13 15:01:40 2007
######################################################################

TEMPLATE = app
TARGET = testapp
DESTDIR = bin
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += testapp.h ../src/ircclient.h
SOURCES += main.cpp testapp.cpp ../src/ircclient.cpp
